import * as fs from "node:fs";
import * as path from "node:path";
import type { MCPServerSpec, ToolDefinition } from "../../core/types.js";
import { relativeImport } from "./extractor.js";

/**
 * Generates a ready-to-run TypeScript MCP server from a spec.
 *
 * The generated server:
 * - Imports the original module directly (no subprocess).
 * - Registers one MCP tool per ToolDefinition.
 * - Handles stdio transport.
 */
export async function generateTypeScript(spec: MCPServerSpec, outputDir: string): Promise<string> {
  const serverFile = path.join(outputDir, "server.ts");
  const moduleImport = relativeImport(outputDir, spec.sourcePath);

  const toolNames = spec.tools.map((t) => t.name);
  const importLine = `import { ${toolNames.join(", ")} } from "${moduleImport}";`;

  const toolRegistrations = spec.tools.map((t) => renderToolRegistration(t)).join("\n\n");

  const serverCode = `#!/usr/bin/env node
/**
 * MCP server generated by mcpify.
 * Source: ${spec.sourcePath}
 * Language: TypeScript
 *
 * DO NOT EDIT — re-run \`mcpify generate\` to update.
 */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
${importLine}

const server = new McpServer({
  name: ${JSON.stringify(spec.moduleName)},
  version: "1.0.0",
});

${toolRegistrations}

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write(\`mcpify: ${spec.moduleName} MCP server running on stdio\\n\`);
}

main().catch((err) => {
  process.stderr.write(\`Fatal: \${err}\\n\`);
  process.exit(1);
});
`;

  fs.writeFileSync(serverFile, serverCode, "utf-8");

  // Write a minimal package.json so the server can be run with tsx/ts-node
  const pkgFile = path.join(outputDir, "package.json");
  if (!fs.existsSync(pkgFile)) {
    fs.writeFileSync(
      pkgFile,
      JSON.stringify(
        {
          name: `${spec.moduleName}-mcp-server`,
          version: "1.0.0",
          type: "module",
          scripts: { start: "tsx server.ts" },
          dependencies: {
            "@modelcontextprotocol/sdk": "^1.26.0",
          },
          devDependencies: { tsx: "^4.19.2" },
        },
        null,
        2,
      ) + "\n",
      "utf-8",
    );
  }

  return serverFile;
}

function renderToolRegistration(tool: ToolDefinition): string {
  const shape = renderZodShape(tool);
  const paramNames = tool.parameters.map((p) => p.name);
  const destructure = paramNames.length > 0 ? `{ ${paramNames.join(", ")} }` : "_args";
  const callArgs = paramNames.join(", ");
  const description = tool.description || `Call ${tool.name}`;

  return `server.tool(
  ${JSON.stringify(tool.name)},
  ${JSON.stringify(description)},
  ${shape},
  async (${destructure}) => {
    const result = await ${tool.name}(${callArgs});
    return {
      content: [{ type: "text", text: String(result) }],
    };
  },
);`;
}

/**
 * Renders an inline z.object({}) shape for the tool's parameters.
 * We generate plain Zod schema strings.
 */
function renderZodShape(tool: ToolDefinition): string {
  if (tool.parameters.length === 0) return "{}";

  const fields = tool.parameters.map((p) => {
    const zodType = schemaToZod(p.schema);
    const desc = p.description ? `.describe(${JSON.stringify(p.description)})` : "";
    const opt = p.required ? "" : ".optional()";
    return `    ${p.name}: ${zodType}${desc}${opt}`;
  });
  return `{\n${fields.join(",\n")}\n  }`;
}

function schemaToZod(schema: import("../../core/types.js").JSONSchema): string {
  if (schema.enum) {
    const members = schema.enum.map((v) => JSON.stringify(v)).join(", ");
    return `z.enum([${members}])`;
  }
  switch (schema.type) {
    case "string":
      return "z.string()";
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "array":
      return `z.array(${schema.items ? schemaToZod(schema.items) : "z.unknown()"})`;
    case "object": {
      if (!schema.properties) return "z.record(z.unknown())";
      const fields = Object.entries(schema.properties)
        .map(([k, v]) => `${k}: ${schemaToZod(v)}`)
        .join(", ");
      return `z.object({ ${fields} })`;
    }
    default:
      return "z.unknown()";
  }
}
