version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"