<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Mcpify.Language.Ruby</AssemblyName>
    <RootNamespace>Mcpify.Language.Ruby</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="toolchain.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Mcpify.Core/Mcpify.Core.csproj" />
  </ItemGroup>
</Project>
