import * as fs from "node:fs";
import * as path from "node:path";
import type { MCPServerSpec, ToolDefinition } from "../../core/types.js";

/**
 * Generates a ready-to-run Go MCP server using the mark3labs/mcp-go SDK.
 *
 * The generated server imports the original package and calls its exported
 * functions directly.
 */
export async function generateGo(spec: MCPServerSpec, outputDir: string): Promise<string> {
  const serverFile = path.join(outputDir, "main.go");

  // Infer the Go module path for the source package.
  // We look for a go.mod in the source tree to determine the module root.
  const modulePath = resolveGoModulePath(spec.sourcePath, outputDir);

  const toolRegistrations = spec.tools.map((t) => renderGoTool(t, modulePath)).join("\n\n");

  const serverCode = `// MCP server generated by mcpify.
// Source: ${spec.sourcePath}
// Language: Go
//
// DO NOT EDIT — re-run \`mcpify generate\` to update.
package main

import (
	"context"
	"fmt"
	"log"

	mcp "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	src "${modulePath}"
)

func main() {
	s := server.NewMCPServer(
		${JSON.stringify(spec.moduleName)},
		"1.0.0",
		server.WithToolCapabilities(false),
	)

${toolRegistrations}

	log.Printf("mcpify: ${spec.moduleName} MCP server running on stdio")
	if err := server.ServeStdio(s); err != nil {
		log.Fatalf("Fatal: %v", err)
	}
}
`;

  fs.writeFileSync(serverFile, serverCode, "utf-8");

  // Write go.mod for the generated server
  const goModFile = path.join(outputDir, "go.mod");
  if (!fs.existsSync(goModFile)) {
    fs.writeFileSync(
      goModFile,
      `module ${spec.moduleName}-mcp-server

go 1.21

require (
\tgithub.com/mark3labs/mcp-go v0.32.0
)
`,
      "utf-8",
    );
  }

  return serverFile;
}

function renderGoTool(tool: ToolDefinition, _modulePath: string): string {
  const opts = tool.parameters
    .map((p) => {
      const goType = schemaToGoType(p.schema);
      const withFn = p.required ? "mcp.Required()" : "";
      return `\t\tmcp.WithArgument(${JSON.stringify(p.name)}, mcp.Description(${JSON.stringify(p.description || "")}), ${goType}${withFn ? `, ${withFn}` : ""}),`;
    })
    .join("\n");

  const argExtracts = tool.parameters
    .map((p) => `\t\t${p.name} := mcp.ParseString(req, ${JSON.stringify(p.name)})`)
    .join("\n");

  const callArgs = tool.parameters.map((p) => p.name).join(", ");
  const description = tool.description || `Call ${tool.name}`;

  return `\t${tool.name}Tool := mcp.NewTool(${JSON.stringify(tool.name)},
\t\tmcp.WithDescription(${JSON.stringify(description)}),
${opts}
\t)
\ts.AddTool(${tool.name}Tool, func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
${argExtracts}
\t\tresult := src.${tool.name}(${callArgs})
\t\treturn mcp.NewToolResultText(fmt.Sprintf("%v", result)), nil
\t})`;
}

function schemaToGoType(schema: import("../../core/types.js").JSONSchema): string {
  switch (schema.type) {
    case "integer":
      return "mcp.Int()";
    case "number":
      return "mcp.Number()";
    case "boolean":
      return "mcp.Bool()";
    case "array":
      return "mcp.Array()";
    case "object":
      return "mcp.Object()";
    default:
      return "mcp.String()";
  }
}

/** Try to determine the Go import path for the source file's package. */
function resolveGoModulePath(sourcePath: string, outputDir: string): string {
  // Walk up from sourcePath looking for go.mod
  let dir = path.dirname(sourcePath);
  while (true) {
    const goMod = path.join(dir, "go.mod");
    if (fs.existsSync(goMod)) {
      const modContent = fs.readFileSync(goMod, "utf-8");
      const match = modContent.match(/^module\s+(\S+)/m);
      if (match) {
        const moduleName = match[1];
        const rel = path.relative(dir, path.dirname(sourcePath)).replace(/\\/g, "/");
        return rel ? `${moduleName}/${rel}` : moduleName;
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: use relative path from outputDir
  const rel = path.relative(outputDir, path.dirname(sourcePath)).replace(/\\/g, "/");
  return `../` + rel;
}
