import * as fs from "node:fs";
import * as path from "node:path";
import type { MCPServerSpec, ToolDefinition } from "../../core/types.js";

/**
 * Generates a ready-to-run Python MCP server using the official `mcp` SDK.
 *
 * The generated server:
 * - Imports functions directly from the original module.
 * - Uses the FastMCP / low-level MCP Python SDK pattern.
 * - Runs over stdio transport.
 */
export async function generatePython(
  spec: MCPServerSpec,
  outputDir: string,
): Promise<string> {
  const serverFile = path.join(outputDir, "server.py");

  // Relative import path from outputDir → spec.sourcePath
  const relPath = path.relative(outputDir, spec.sourcePath).replace(/\\/g, "/");
  // Convert file path to Python module notation: strip .py, convert / to .
  const modulePath = relPath.replace(/\.py$/, "").replace(/\//g, ".").replace(/^\.+/, "");

  const toolNames = spec.tools.map((t) => t.name);
  const importLine = `from ${modulePath} import ${toolNames.join(", ")}`;

  const toolRegistrations = spec.tools.map((t) => renderPythonTool(t)).join("\n\n");

  const serverCode = `#!/usr/bin/env python3
"""
MCP server generated by mcpify.
Source: ${spec.sourcePath}
Language: Python

DO NOT EDIT — re-run \`mcpify generate\` to update.
"""
import sys
import asyncio
import json
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp import types as mcp_types
${importLine}

server = Server(${JSON.stringify(spec.moduleName)})


@server.list_tools()
async def list_tools() -> list[mcp_types.Tool]:
    return [
${spec.tools.map((t) => renderPythonToolMeta(t)).join(",\n")}
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[mcp_types.TextContent]:
    match name:
${spec.tools.map((t) => renderPythonToolDispatch(t)).join("\n")}
        case _:
            raise ValueError(f"Unknown tool: {name}")


async def main() -> None:
    print(f"mcpify: ${spec.moduleName} MCP server running on stdio", file=sys.stderr)
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


if __name__ == "__main__":
    asyncio.run(main())
`;

  fs.writeFileSync(serverFile, serverCode, "utf-8");

  // Write a requirements.txt
  const reqFile = path.join(outputDir, "requirements.txt");
  if (!fs.existsSync(reqFile)) {
    fs.writeFileSync(reqFile, "mcp>=1.0.0\n", "utf-8");
  }

  return serverFile;
}

function renderPythonToolMeta(tool: ToolDefinition): string {
  const description = tool.description || `Call ${tool.name}`;
  const schemaStr = JSON.stringify(tool.inputSchema, null, 4)
    .split("\n")
    .join("\n            ");
  return `        mcp_types.Tool(
            name=${JSON.stringify(tool.name)},
            description=${JSON.stringify(description)},
            inputSchema=${schemaStr},
        )`;
}

function renderPythonToolDispatch(tool: ToolDefinition): string {
  const paramNames = tool.parameters.map((p) => p.name);
  const kwArgs = paramNames
    .map((n) => `${n}=arguments.get(${JSON.stringify(n)})`)
    .join(", ");
  const callExpr = `${tool.name}(${kwArgs})`;
  return `        case ${JSON.stringify(tool.name)}:
            result = ${callExpr}
            return [mcp_types.TextContent(type="text", text=str(result))]`;
}
